CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AlertSenders" (
    "Id" uuid NOT NULL,
    "Code" character varying(6) NOT NULL,
    "Name" character varying(256) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "ModifiedOn" timestamp with time zone,
    "ModifiedBy" uuid,
    "DeletedOn" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_AlertSenders" PRIMARY KEY ("Id")
);

CREATE TABLE "AlertTypes" (
    "Id" uuid NOT NULL,
    "ProductCode" character varying(6) NOT NULL,
    "Name" character varying(256) NOT NULL,
    "Description" character varying(4096) NOT NULL,
    "Level" text NOT NULL,
    "EventCode" character varying(6),
    "TypeCode" text GENERATED ALWAYS AS (COALESCE("EventCode", "ProductCode")) STORED NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "ModifiedOn" timestamp with time zone,
    "ModifiedBy" uuid,
    "DeletedOn" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_AlertTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "Events" (
    "Id" uuid NOT NULL,
    "Type" character varying(256) NOT NULL,
    "Payload" text NOT NULL,
    "Failures" integer NOT NULL,
    "HandledOn" timestamp with time zone,
    CONSTRAINT "PK_Events" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "ModifiedOn" timestamp with time zone,
    "ModifiedBy" uuid,
    "DeletedOn" timestamp with time zone,
    "DeletedBy" uuid,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "ModifiedOn" timestamp with time zone,
    "ModifiedBy" uuid,
    "DeletedOn" timestamp with time zone,
    "DeletedBy" uuid,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Zones" (
    "Id" uuid NOT NULL,
    "Code" character varying(6) NOT NULL,
    "Name" character varying(256) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "ModifiedOn" timestamp with time zone,
    "ModifiedBy" uuid,
    "DeletedOn" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_Zones" PRIMARY KEY ("Id")
);

CREATE TABLE "Alerts" (
    "Id" uuid NOT NULL,
    "TypeId" uuid NOT NULL,
    "SenderId" uuid NOT NULL,
    "Headline" character varying(256) NOT NULL,
    "Description" character varying(4096) NOT NULL,
    "Instruction" character varying(4096) NOT NULL,
    "SentOn" timestamp with time zone NOT NULL,
    "EffectiveOn" timestamp with time zone NOT NULL,
    "BeginsOn" timestamp with time zone NOT NULL,
    "ExpiresOn" timestamp with time zone NOT NULL,
    "EndsOn" timestamp with time zone NOT NULL,
    "MessageType" text NOT NULL,
    "Severity" text NOT NULL,
    "Certainty" text NOT NULL,
    "Urgency" text NOT NULL,
    "Response" text NOT NULL,
    "IsEffectuated" boolean NOT NULL,
    "IsExpired" boolean NOT NULL,
    "ExternalId" text,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "ModifiedOn" timestamp with time zone,
    "ModifiedBy" uuid,
    "DeletedOn" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_Alerts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Alerts_AlertSenders_SenderId" FOREIGN KEY ("SenderId") REFERENCES "AlertSenders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Alerts_AlertTypes_TypeId" FOREIGN KEY ("TypeId") REFERENCES "AlertTypes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserLogins" (
    "LoginProvider" character varying(256) NOT NULL,
    "ProviderKey" character varying(256) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" character varying(256) NOT NULL,
    "Name" character varying(256) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AlertParameters" (
    "Id" uuid NOT NULL,
    "Key" character varying(256) NOT NULL,
    "Value" character varying(4096) NOT NULL,
    "AlertId" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "ModifiedOn" timestamp with time zone,
    "ModifiedBy" uuid,
    "DeletedOn" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_AlertParameters" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AlertParameters_Alerts_AlertId" FOREIGN KEY ("AlertId") REFERENCES "Alerts" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AlertZones" (
    "Id" uuid NOT NULL,
    "AlertId" uuid NOT NULL,
    "ZoneId" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "ModifiedOn" timestamp with time zone,
    "ModifiedBy" uuid,
    "DeletedOn" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_AlertZones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AlertZones_Alerts_AlertId" FOREIGN KEY ("AlertId") REFERENCES "Alerts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AlertZones_Zones_ZoneId" FOREIGN KEY ("ZoneId") REFERENCES "Zones" ("Id") ON DELETE CASCADE
);

INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('001382ad-4143-4075-960b-e25939d38c14', 'TOP', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Topeka');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('043d5214-8653-4ea4-a7c9-cdc8487d1ccb', 'RAH', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Raleigh North');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('06f137a5-aa58-4151-ad4d-999bde3965fd', 'BIS', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Bismarck');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('0c1785b4-e0ee-41cf-9862-340dd2a5f7ff', 'MTR', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS San Francisco Bay Area');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('0de3e30b-14a6-4411-9897-9e3ab8585681', 'OTX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Spokane');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('11035a3c-5bea-46e4-bea5-a1733fe59b53', 'EPZ', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS El Paso');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('12f93626-4d50-408e-91a3-b6cdf406ef2d', 'FSD', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Sioux Fall');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('12f9c72d-97ce-4e82-aeb5-7a7ae999a6c8', 'TBW', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Tampa');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('145c5051-c688-4487-a803-e83f4fcabc1e', 'RLX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Charlesto');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('17b93477-b647-420b-bcc0-75eefb6734d1', 'TSA', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Tulsa');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('1833e572-775d-42e8-a10d-894947ba4c72', 'JKL', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Jackson');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('19c76882-fb3d-488a-8e9d-a7dd67bb3940', 'MLB', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Melbourne');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('1c9e022b-975f-411f-b890-bad1ba9a7cca', 'AMA', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Amarillo');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('1dd67163-cb82-4f18-9a7e-399728669a78', 'ILM', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Wilmington');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('1ee7055c-b229-41e4-ae10-0d6019531b71', 'PIH', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Pocatello');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('20e3a576-f20b-4c93-9558-4bfe90fe1503', 'UNR', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Rapid City');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('2f714d64-8bcc-4b56-ab34-fadddece36f7', 'SGF', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Springfield');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('306fb3e4-897a-4ef5-bcf7-607232c4a897', 'BUF', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Buffalo');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('30abad4d-994c-4592-9a6e-7adfc49751f6', 'LKN', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Elko');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('3459fab2-416c-4ead-a5a1-c363bcc37806', 'TWC', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Tucson');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('36600f01-c7cf-4d9c-a14d-898f48dafe4c', 'FGZ', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Flagstaff');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('377c698f-fe43-48cb-9df6-52af611cb08c', 'GSP', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Greenville/Spartanburg');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('37cf2a4a-9c9c-4c01-96a3-3ac4f392505f', 'LWX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Baltimore/Washington');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('38e3c394-1b3e-479e-8400-3dbb76fddd7f', 'EKA', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Eureka');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('38feda61-88ca-4d20-90b1-06e65e9e7f11', 'LBF', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS North Platte');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('3b567347-e762-4598-a750-e9f58ae4903c', 'TAE', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Tallahassee');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('3d595d50-0216-456b-b95e-416ad2c7771e', 'OHX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Nashville');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('4350f374-9061-4c6f-bf5c-2bae508b8129', 'LMK', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Louisville');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('4385ba25-5a19-4928-9433-37df725f4752', 'BOX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Boston/Norton');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('468481f8-7ac3-4d62-9873-e086d1c349c5', 'EWX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Austin/San Antonio');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('4b2169a9-c48c-4372-8a98-693f4e7ca190', 'LSX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS St. Louis');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('4d07a497-918e-4ed9-bcac-a94424521152', 'MSO', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Missoula');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('4d99506c-6023-4708-b48c-06f8e534d6ba', 'HFO', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Honolulu');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('4e4e6437-65d6-4505-b7b7-005d99cf182e', 'HGX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Houston/Galveston');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('4fd91921-a691-4684-824a-8dcdde63bca9', 'LCH', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Lake Charles');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('501e077f-b558-48ec-98fc-26413d0d27ad', 'GGW', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Glasgow');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('52c35b4a-653b-46f1-bd82-0e474c75893f', 'AFC', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Anchorage');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('53ab0911-8a41-4a93-bd2d-93220f9cf4dd', 'HNX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS San Joaquin Valley');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('59a6c9a8-95db-4d8a-8038-02962e10fe14', 'ILX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Lincoln');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('5a3bbe70-5f16-4290-959c-ec8813a2ae82', 'LOT', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Chicago');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('5a8ca515-8cf2-4213-a974-fb1317e7e649', 'FWD', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Fort Worth/Dallas');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('5acdae5e-4b49-4053-bf43-2b0083512882', 'ARX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS La Crosse');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('5c1e32a7-7077-4097-a94f-0c32d21dd08a', 'REV', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Reno');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('5f85bc59-5a63-4052-b8bc-592193317846', 'LZK', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Little Rock');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('5fcf256c-d0ca-4533-b7e2-e8cce2514c47', 'GRR', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Grand Rapids');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('63bacad6-0460-4ef9-bad5-7214ba9b5fe7', 'MRX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Morristown');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('65877500-3987-49bc-9db8-e71265d742be', 'PAH', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Paducah');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('668d6067-e7c9-47fc-8269-c9c6a4cbf1aa', 'PSR', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Phoenix');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('6ba0bf0b-cdb6-456f-9d71-66bdc8128ea2', 'ICT', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Wichita');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('6d80e8f5-d7fe-45dc-91f2-70ef33d69c02', 'GLD', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Goodland');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('70cf1e8a-1cec-4a3b-8e65-939ecb780622', 'DLH', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Duluth');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('7216a99c-49b2-446c-971f-849ea0642b10', 'MQT', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Marquette');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('7a1e9a80-499b-41aa-aada-bb0fba9b3efb', 'TFX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Great Falls');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('7db25e25-a0d7-4237-8163-d732a2366fbc', 'DDC', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Dodge City');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('82899735-8877-4c12-b8a0-e679cbe1582a', 'CRP', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Corpus Christi');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('847700b4-2040-4669-8904-73f85be84b88', 'RNK', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Blacksburg');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('8505dace-9d60-431c-a7ef-278ce6ffc5b6', 'MHX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Newport/Morehead City');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('879c0b7e-24ce-4deb-abda-51a2ee90b6c0', 'SJT', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS San Angelo');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('8a2c6cb5-82ce-4e17-a778-e4adfaef7056', 'GJT', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Grand Junction');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('8cd29888-8dc8-40e9-bf97-76bb3761ed80', 'IWX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Northern Indiana');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('8f63fbe1-3e28-4fdd-983b-0a2844bcc59b', 'MPX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Twin Cities');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('8fd8f311-3dc2-427e-8182-dfc45549cee0', 'PHI', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Mount Holly/Philadelphia');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('9081c006-67ad-486c-b9b6-d75d961ea004', 'MOB', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Mobile/Pensacola');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('9318342e-964e-4af4-98c7-98f459d012d1', 'GUM', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Guam');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('9678f207-df1b-428e-8397-a184f3a0ee48', 'KEY', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Key West');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('97969901-52ca-437d-a226-770dfc538f50', 'LUB', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Lubbock');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('9871fad4-16b2-4c66-8e57-45e98644dbb4', 'LOX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Los Angeles');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('a0af1fea-d647-42cd-b5b8-f55b89009ef2', 'MKX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Milwaukee/Sullivan');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('a16b9285-7d53-4707-85b8-2bec5de37f29', 'BYZ', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Billings');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('a60b1be3-122e-429d-a31c-4b22e29b8f9f', 'ABR', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Aberdee');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('a8578756-e0c0-4b44-86bf-b54d20181964', 'BMX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Birmingham');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('a9203129-327c-4e08-8d18-97e3a879f299', 'MFR', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Medford');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('ac3ac668-301c-4e9c-89e6-f0b2fcf5de56', 'BGM', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Binghamton');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('ac7b3431-6ee2-4f8e-8e0f-1fc1523da6b3', 'SLC', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Salt Lake City');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('ada98b38-ea71-49a6-9066-86c6e94e0ae9', 'DMX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Des Moines');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('adfcd9cf-b147-4e8d-984c-888884dbcb09', 'SEW', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Seattle');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('aff2166a-dc65-4dbb-b112-06f84b30cc50', 'GID', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Hastings');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('b03efd4a-a90d-4514-9eff-a011ac77d256', 'MFL', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Miami');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('b08b0b49-fb75-46a5-8d0a-a60240a79e3a', 'PUB', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Pueblo');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('b3a78ffd-37a2-4663-928f-81feb479d205', 'CHS', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Charlesto');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('b513fcfc-40ff-480c-a73a-9c4a6823d729', 'APX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Gaylord');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('b886c96b-c07d-4dbc-afe6-ce4dc1e22b33', 'MEG', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Memphis');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('b9984c93-c83a-4574-baa3-39951034b4ba', 'JAN', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Jackson');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('b99be2df-a3df-4dc2-8509-565626817412', 'DTX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Detroit/Pontiac');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('bb03d5e5-a868-485e-aa14-c6c157d95036', 'FFC', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Peachtree City');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('bc6c324b-5cd8-4f54-907e-d0845f11444d', 'GYX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Gray/Portland');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('bdcd24b8-12fb-4dc2-94c3-e81ee547f90e', 'PDT', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Pendleton');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('bf6ebce9-528b-407f-a9cb-0a19db00ff81', 'SGX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS San Diego');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('c1248289-4f30-49dd-8988-c24e05d6bcd3', 'HUN', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Huntsville');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('c3c91064-75c3-44e1-91c5-feb79f6e819c', 'CYS', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Cheyenne');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('ca12e950-6b48-4f5d-b992-b386a800d009', 'LIX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS New Orleans/Baton Rouge');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('cc5c48f4-196e-4673-92ed-45d62bf61d0b', 'OUN', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Norman');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('cde34b64-e24c-4af9-ba4e-56c371b2ff12', 'FGF', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Grand Fork');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('d0386bc4-d1e6-4ab9-a525-3f97a8fda648', 'PBZ', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Pittsburgh');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('d55e1e3c-aae1-49df-ab3d-90406e37bd12', 'GRB', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Green Bay');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('d8bd481c-d915-4bba-bc88-a7cf70ce4e4e', 'CAR', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Caribou');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('d9ec8bb2-7859-488b-82d0-c7cccee874e5', 'CTP', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS State College');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('da48fcf2-9a36-4cdc-abab-c1734a650ac2', 'ILN', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Wilmington');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('db1a00b0-3412-4fa7-b0b4-30bbbcda7a2d', 'MAF', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Midland/Odessa');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('dc47825b-4ebc-4afc-9cc3-91593ce3beee', 'STO', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Sacramento');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('dfc086c9-3a68-4368-b77a-c69f7f018aa9', 'IND', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Indianapolis');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('e0a630eb-4707-4738-9a90-d901aab30d54', 'RIW', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Riverton');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('e13cde99-0296-4832-8c5f-e7ae4115d26c', 'OKX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS New York');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('e23cb76a-757a-4317-a8e6-9dcd9efdfcf5', 'EAX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Kansas City/Pleasant Hill');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('e34917c4-1212-4e08-8299-e3a5896fc982', 'CAE', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Columbia');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('e4172543-8af7-49c5-9c6a-bb0074c47870', 'BTV', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Burlington');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('e85d5721-df68-44bb-8b33-d7bc0085e3a2', 'PQR', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Portland');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('e86bf576-78fb-4065-ab44-e934b7959e4a', 'AFG', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Fairbanks');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('e8e52f2a-a403-4cc1-a550-c651dcb607c3', 'SJU', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS San Jua');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('eac912a6-595b-4166-b816-660bfcedeffa', 'AKQ', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Wakefield');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('ead8d492-74f8-46ed-a590-223329debeca', 'SHV', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Shreveport');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('ec13a114-e78e-4c65-9d00-bb5140d36329', 'BOU', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Denver/Boulder');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('ec9c708a-f0a2-4fb8-a9fb-77dafc6483d4', 'ALY', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Albany');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('f04af92c-8c67-4a49-859f-79252c135a7b', 'BOI', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Boise');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('f04e98af-86f7-4535-babf-6e729ff84275', 'ABQ', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Albuquerque');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('f34dc1bd-fe8d-4f39-98f6-25977a0b0800', 'CLE', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Cleveland');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('f439c86f-50ae-4e51-819d-c3269506b1f1', 'VEF', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Las Vegas');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('f468413b-b9d3-4590-aeb3-fea78abbec2f', 'JAX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Jacksonville');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('fa675f2a-f105-48f2-8219-4beb767d1ec4', 'OAX', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Omaha/Valley');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('fc8e9ba3-ddd1-4fa9-9656-5e85e846a534', 'DVN', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Quad Cities');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('fe44cb6c-65d3-48cb-9ae8-7f3e5735d871', 'BRO', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Brownsville');
INSERT INTO "AlertSenders" ("Id", "Code", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name")
VALUES ('ff7f49da-b154-4fd5-980d-1790046c4c58', 'AJK', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'NWS Juneau');

INSERT INTO "AlertTypes" ("Id", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "Description", "EventCode", "Level", "ModifiedBy", "ModifiedOn", "Name", "ProductCode")
VALUES ('43f44630-21db-4421-871d-f2d327489552', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, 'Issued to inform the public, emergency management, and other cooperating agencies that flash flooding is in progress, imminent, or highly likely.', 'FFW', 'Warning', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'Flash Flood Warning', 'FFW');
INSERT INTO "AlertTypes" ("Id", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "Description", "EventCode", "Level", "ModifiedBy", "ModifiedOn", "Name", "ProductCode")
VALUES ('4a4461ce-2b48-4dfb-938b-e40a8ce35437', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, 'A weather statement issued when a specified hazard is approaching advisory criteria or to highlight upcoming significant weather events. These are issued to advise of ongoing or imminent hazardous convective weather expected to continue/dissipate or expand/decrease in geographical coverage within the next one to two hours, major events forecast to occur beyond a six-hour timeframe (such as substantial temperature changes, dense fog and winter weather events), sub-severe thunderstorms (containing sustained winds or gusts of 40–57 mph (64–92 km/h) and/or hail less than one inch (2.5 cm) in diameter, in addition to frequent to continuous lightning and/or funnel clouds not expected to become a tornado threat), or to outline high-impact events supplementary to information contained in other hazardous weather products (such as black ice, short-duration heavy snow or lake-effect snow bands expected to briefly reduce visibility, heavy rainfall not expected to cause flooding, heat index or wind chill values expected to approach "advisory" criteria for one or two hours, or local areas of blowing dust where wind is below advisory criteria).', NULL, 'Advisory', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'Special Weather Statement', 'SPS');
INSERT INTO "AlertTypes" ("Id", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "Description", "EventCode", "Level", "ModifiedBy", "ModifiedOn", "Name", "ProductCode")
VALUES ('4a4f23be-9135-4bcb-bb19-7f39a8a8a25d', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, 'This is issued by the National Weather Service when conditions are favorable for the development of tornadoes in and close to the watch area. Their size can vary depending on the weather situation. They are usually issued for a duration of 4 to 8 hours. They normally are issued well in advance of the actual occurrence of severe weather. During the watch, people should review tornado safety rules and be prepared to move a place of safety if threatening weather approaches.', 'TOA', 'Watch', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'Tornado Watch', 'WOU');
INSERT INTO "AlertTypes" ("Id", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "Description", "EventCode", "Level", "ModifiedBy", "ModifiedOn", "Name", "ProductCode")
VALUES ('5434ef57-6bd0-4dda-8e72-bde8fc4bb7d5', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, 'In hydrologic terms, a statement by the NWS which provides follow-up information on flash flood watches and warnings.', 'FFS', 'Advisory', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'Flash Flood Statement', 'FFS');
INSERT INTO "AlertTypes" ("Id", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "Description", "EventCode", "Level", "ModifiedBy", "ModifiedOn", "Name", "ProductCode")
VALUES ('5e82b31c-c3f7-4911-8d54-2944d6782ba8', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, 'This is issued when a tornado is indicated by the WSR-88D radar or sighted by spotters; therefore, people in the affected area should seek safe shelter immediately. They can be issued without a Tornado Watch being already in effect. They are usually issued for a duration of around 30 minutes.', 'TOW', 'Warning', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'Tornado Warning', 'TOR');
INSERT INTO "AlertTypes" ("Id", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "Description", "EventCode", "Level", "ModifiedBy", "ModifiedOn", "Name", "ProductCode")
VALUES ('a312351a-fb7b-40bd-9e9d-685d0840ed01', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, 'Issued to indicate current or developing hydrologic conditions that are favorable for flash flooding in and close to the watch area, but the occurrence is neither certain or imminent.', 'FFA', 'Watch', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'Flash Flood Watch', 'FFA');
INSERT INTO "AlertTypes" ("Id", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "Description", "EventCode", "Level", "ModifiedBy", "ModifiedOn", "Name", "ProductCode")
VALUES ('a349126f-92f1-4222-a3cf-bd105b7764f5', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, 'This is issued when either a severe thunderstorm is indicated by the WSR-88D radar or a spotter reports a thunderstorm producing hail one inch or larger in diameter and/or winds equal or exceed 58 miles an hour; therefore, people in the affected area should seek safe shelter immediately. Severe thunderstorms can produce tornadoes with little or no advance warning. Lightning frequency is not a criteria for issuing a severe thunderstorm warning. They are usually issued for a duration of one hour. They can be issued without a Severe Thunderstorm Watch being already in effect.', 'SVW', 'Warning', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'Severe Thunderstorm Warning', 'SVR');
INSERT INTO "AlertTypes" ("Id", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "Description", "EventCode", "Level", "ModifiedBy", "ModifiedOn", "Name", "ProductCode")
VALUES ('be8f23f2-23b1-4f6a-9919-e48d854cb243', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, 'This is issued by the National Weather Service when conditions are favorable for the development of severe thunderstorms in and close to the watch area. A severe thunderstorm by definition is a thunderstorm that produces one inch hail or larger in diameter and/or winds equal or exceed 58 miles an hour. The size of the watch can vary depending on the weather situation. They are usually issued for a duration of 4 to 8 hours. They are normally issued well in advance of the actual occurrence of severe weather. During the watch, people should review severe thunderstorm safety rules and be prepared to move a place of safety if threatening weather approaches.', 'SVA', 'Watch', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'Severe Thunderstorm Watch', 'WOU');
INSERT INTO "AlertTypes" ("Id", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "Description", "EventCode", "Level", "ModifiedBy", "ModifiedOn", "Name", "ProductCode")
VALUES ('c8a66177-6201-4d9b-b007-f66a7cc090a3', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, 'A National Weather Service product which provides follow up information on severe weather conditions (severe thunderstorm or tornadoes) which have occurred or are currently occurring.', NULL, 'Advisory', '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'Severe Weather Statement', 'SVS');

INSERT INTO "Roles" ("Id", "ConcurrencyStamp", "CreatedBy", "CreatedOn", "DeletedBy", "DeletedOn", "ModifiedBy", "ModifiedOn", "Name", "NormalizedName")
VALUES ('951eb04f-9b26-4f6d-a807-57edfa277efa', NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', NULL, NULL, '11111111-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-05-25T00:00:00+00:00', 'Admin', NULL);

CREATE INDEX "IX_AlertParameters_AlertId" ON "AlertParameters" ("AlertId");

CREATE INDEX "IX_AlertParameters_CreatedOn" ON "AlertParameters" ("CreatedOn");

CREATE INDEX "IX_AlertParameters_DeletedOn" ON "AlertParameters" ("DeletedOn");

CREATE INDEX "IX_AlertParameters_Key" ON "AlertParameters" ("Key");

CREATE INDEX "IX_AlertParameters_ModifiedOn" ON "AlertParameters" ("ModifiedOn");

CREATE INDEX "IX_Alerts_CreatedOn" ON "Alerts" ("CreatedOn");

CREATE INDEX "IX_Alerts_DeletedOn" ON "Alerts" ("DeletedOn");

CREATE INDEX "IX_Alerts_EffectiveOn" ON "Alerts" ("EffectiveOn");

CREATE INDEX "IX_Alerts_ExpiresOn" ON "Alerts" ("ExpiresOn");

CREATE INDEX "IX_Alerts_ModifiedOn" ON "Alerts" ("ModifiedOn");

CREATE INDEX "IX_Alerts_SenderId" ON "Alerts" ("SenderId");

CREATE INDEX "IX_Alerts_TypeId" ON "Alerts" ("TypeId");

CREATE INDEX "IX_AlertSenders_Code" ON "AlertSenders" ("Code");

CREATE INDEX "IX_AlertSenders_CreatedOn" ON "AlertSenders" ("CreatedOn");

CREATE INDEX "IX_AlertSenders_DeletedOn" ON "AlertSenders" ("DeletedOn");

CREATE INDEX "IX_AlertSenders_ModifiedOn" ON "AlertSenders" ("ModifiedOn");

CREATE INDEX "IX_AlertTypes_CreatedOn" ON "AlertTypes" ("CreatedOn");

CREATE INDEX "IX_AlertTypes_DeletedOn" ON "AlertTypes" ("DeletedOn");

CREATE INDEX "IX_AlertTypes_EventCode" ON "AlertTypes" ("EventCode");

CREATE INDEX "IX_AlertTypes_ModifiedOn" ON "AlertTypes" ("ModifiedOn");

CREATE INDEX "IX_AlertTypes_ProductCode" ON "AlertTypes" ("ProductCode");

CREATE UNIQUE INDEX "IX_AlertTypes_ProductCode_EventCode" ON "AlertTypes" ("ProductCode", "EventCode");

CREATE INDEX "IX_AlertZones_AlertId" ON "AlertZones" ("AlertId");

CREATE INDEX "IX_AlertZones_CreatedOn" ON "AlertZones" ("CreatedOn");

CREATE INDEX "IX_AlertZones_DeletedOn" ON "AlertZones" ("DeletedOn");

CREATE INDEX "IX_AlertZones_ModifiedOn" ON "AlertZones" ("ModifiedOn");

CREATE INDEX "IX_AlertZones_ZoneId" ON "AlertZones" ("ZoneId");

CREATE INDEX "IX_Events_Type" ON "Events" ("Type");

CREATE INDEX "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");

CREATE INDEX "IX_Roles_CreatedOn" ON "Roles" ("CreatedOn");

CREATE INDEX "IX_Roles_DeletedOn" ON "Roles" ("DeletedOn");

CREATE INDEX "IX_Roles_ModifiedOn" ON "Roles" ("ModifiedOn");

CREATE UNIQUE INDEX "RoleNameIndex" ON "Roles" ("NormalizedName");

CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");

CREATE INDEX "IX_UserLogins_UserId" ON "UserLogins" ("UserId");

CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "Users" ("NormalizedEmail");

CREATE INDEX "IX_Users_CreatedOn" ON "Users" ("CreatedOn");

CREATE INDEX "IX_Users_DeletedOn" ON "Users" ("DeletedOn");

CREATE INDEX "IX_Users_ModifiedOn" ON "Users" ("ModifiedOn");

CREATE UNIQUE INDEX "UserNameIndex" ON "Users" ("NormalizedUserName");

CREATE UNIQUE INDEX "IX_Zones_Code" ON "Zones" ("Code");

CREATE INDEX "IX_Zones_CreatedOn" ON "Zones" ("CreatedOn");

CREATE INDEX "IX_Zones_DeletedOn" ON "Zones" ("DeletedOn");

CREATE INDEX "IX_Zones_ModifiedOn" ON "Zones" ("ModifiedOn");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250525002000_Initial', '9.0.5');

COMMIT;

