# Builds the project and executes tests.

name: Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '20.x'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: List Directory
    - run: ls

    - name: Restore Dependencies
      run: dotnet restore ./Skylight
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      

